#!/usr/bin/env bash
#
# Reattend Enterprise — one-shot droplet setup.
#
# Run this as ROOT on a fresh Ubuntu 24.04 DigitalOcean droplet. It installs
# everything: Node, Docker, nginx, certbot, UFW, Reattend app, Nango
# self-hosted, SSL. Idempotent — running twice is safe.
#
# Prereqs before running:
#   - DNS A records: enterprise.reattend.com + nango.reattend.com point here
#   - Repo code available (either pushed to Git or rsync'd to /home/reattend/src)
#
# Usage:
#   export GIT_REPO_URL="https://<token>@github.com/YOU/reattend-enterprise.git"
#   export ANTHROPIC_API_KEY="sk-ant-..."
#   export LETSENCRYPT_EMAIL="ops@reattend.com"
#   curl -fsSL <this-script-url> | bash
#
# Or, if you rsync'd the code instead of using Git:
#   export USE_RSYNC=1
#   bash droplet-setup.sh

set -euo pipefail

DOMAIN_APP="${DOMAIN_APP:-enterprise.reattend.com}"
DOMAIN_NANGO="${DOMAIN_NANGO:-nango.reattend.com}"
APP_USER="reattend"
APP_DIR="/home/${APP_USER}/reattend-enterprise"
DATA_DIR="/home/${APP_USER}/data"
NODE_VERSION="20"
LETSENCRYPT_EMAIL="${LETSENCRYPT_EMAIL:-admin@$(hostname -f 2>/dev/null || echo localhost)}"

log() { echo -e "\n\033[1;36m▸ $*\033[0m"; }
die() { echo -e "\033[1;31m✗ $*\033[0m" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run as root (sudo su; then bash this script)"

# ─── 1. Base packages ─────────────────────────────────────────
log "Installing base packages"
apt-get update -y
DEBIAN_FRONTEND=noninteractive apt-get install -y \
  ufw fail2ban nginx certbot python3-certbot-nginx \
  git build-essential python3 sqlite3 ca-certificates curl gnupg lsb-release

# ─── 2. Firewall ──────────────────────────────────────────────
log "Configuring firewall"
ufw allow OpenSSH >/dev/null
ufw allow 'Nginx Full' >/dev/null
echo "y" | ufw enable >/dev/null || true
ufw status verbose | head -5

# ─── 3. Docker ────────────────────────────────────────────────
if ! command -v docker >/dev/null; then
  log "Installing Docker Engine"
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
else
  log "Docker already installed: $(docker --version)"
fi

# ─── 4. Node.js ───────────────────────────────────────────────
if ! command -v node >/dev/null || [[ "$(node -v)" != v${NODE_VERSION}* ]]; then
  log "Installing Node.js ${NODE_VERSION}"
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_VERSION}.x" | bash -
  apt-get install -y nodejs
else
  log "Node already installed: $(node -v)"
fi

# ─── 5. App user ──────────────────────────────────────────────
if ! id "$APP_USER" &>/dev/null; then
  log "Creating user '$APP_USER'"
  adduser --disabled-password --gecos '' "$APP_USER"
fi
usermod -aG docker "$APP_USER"
mkdir -p "$DATA_DIR" "$DATA_DIR/backups"
chown -R "$APP_USER:$APP_USER" "$DATA_DIR"

# ─── 6. Clone or reuse repo ───────────────────────────────────
if [[ -n "${USE_RSYNC:-}" ]]; then
  log "USE_RSYNC=1 — expecting code already at $APP_DIR (skipping clone)"
  [[ -d "$APP_DIR" ]] || die "$APP_DIR does not exist. rsync your code there first."
elif [[ ! -d "$APP_DIR/.git" ]]; then
  [[ -n "${GIT_REPO_URL:-}" ]] || die "Set GIT_REPO_URL=<clone URL> or USE_RSYNC=1"
  log "Cloning repo"
  sudo -u "$APP_USER" git clone "$GIT_REPO_URL" "$APP_DIR"
else
  log "Pulling latest"
  sudo -u "$APP_USER" bash -c "cd '$APP_DIR' && git pull --ff-only"
fi
chown -R "$APP_USER:$APP_USER" "$APP_DIR"

# ─── 7. App env ───────────────────────────────────────────────
ENV_FILE="$APP_DIR/.env.local"
if [[ ! -f "$ENV_FILE" ]]; then
  log "Generating .env.local (fill in API keys after this script finishes)"
  NEXTAUTH_SECRET_GENERATED="$(openssl rand -hex 32)"
  sudo -u "$APP_USER" tee "$ENV_FILE" >/dev/null <<EOF
# Generated by droplet-setup.sh on $(date -Iseconds)
NEXTAUTH_SECRET=${NEXTAUTH_SECRET_GENERATED}
NEXTAUTH_URL=https://${DOMAIN_APP}
NEXT_PUBLIC_BASE_URL=https://${DOMAIN_APP}
DATABASE_PATH=${DATA_DIR}/reattend.db
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
GROQ_API_KEY=${GROQ_API_KEY:-}
RABBIT_API_URL=${RABBIT_API_URL:-}
RABBIT_API_KEY=${RABBIT_API_KEY:-}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
RESEND_API_KEY=${RESEND_API_KEY:-}
ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY:-}
NANGO_HOST=https://${DOMAIN_NANGO}
# NANGO_SECRET_KEY filled in after first Nango boot (see step 10)
# NANGO_WEBHOOK_SECRET=
EOF
else
  log ".env.local exists, leaving as-is"
fi

# ─── 8. npm install + build ───────────────────────────────────
log "npm ci + build (can take 3-5 minutes)"
sudo -u "$APP_USER" bash -c "cd '$APP_DIR' && npm ci"
sudo -u "$APP_USER" bash -c "cd '$APP_DIR' && npm run build"

# ─── 9. Apply migrations ──────────────────────────────────────
log "Applying database migrations"
sudo -u "$APP_USER" bash -c "cd '$APP_DIR' && DATABASE_PATH='$DATA_DIR/reattend.db' npx drizzle-kit migrate || true"

# ─── 10. Nango stack ──────────────────────────────────────────
NANGO_ENV="$APP_DIR/.env.nango"
if [[ ! -f "$NANGO_ENV" ]]; then
  log "Generating Nango .env"
  sudo -u "$APP_USER" tee "$NANGO_ENV" >/dev/null <<EOF
NANGO_ENCRYPTION_KEY=$(openssl rand -base64 32)
NANGO_SERVER_URL=https://${DOMAIN_NANGO}
NANGO_DB_PASSWORD=$(openssl rand -hex 16)
NANGO_DB_USER=nango
NANGO_DB_NAME=nango
EOF
fi

log "Bringing up Nango (docker compose)"
sudo -u "$APP_USER" bash -c "cd '$APP_DIR' && docker compose -f docker-compose.nango.yml --env-file .env.nango up -d"
sleep 20
log "Nango health check"
curl -sS http://localhost:3003/api/v1/meta >/dev/null && echo "  ✓ Nango server responding" || echo "  ⚠ Nango not yet responding — check 'docker compose -f docker-compose.nango.yml logs' on the droplet"

# ─── 11. systemd unit ─────────────────────────────────────────
log "Installing systemd unit"
cat >/etc/systemd/system/reattend.service <<EOF
[Unit]
Description=Reattend Enterprise (Next.js)
After=network.target

[Service]
Type=simple
User=${APP_USER}
WorkingDirectory=${APP_DIR}
EnvironmentFile=${ENV_FILE}
Environment=NODE_ENV=production
Environment=PORT=3000
ExecStart=/usr/bin/npm run start
Restart=always
RestartSec=5
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable reattend
systemctl restart reattend
sleep 3
log "Reattend service status"
systemctl status reattend --no-pager | head -12 || true

# ─── 12. Nginx ────────────────────────────────────────────────
log "Configuring nginx"
cat >/etc/nginx/sites-available/reattend <<EOF
server {
  listen 80;
  server_name ${DOMAIN_APP};

  client_max_body_size 25m;

  location / {
    proxy_pass http://127.0.0.1:3000;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_read_timeout 300;
    proxy_buffering off;
  }
}

server {
  listen 80;
  server_name ${DOMAIN_NANGO};

  client_max_body_size 10m;

  location / {
    proxy_pass http://127.0.0.1:3003;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_read_timeout 300;
  }
}
EOF
ln -sf /etc/nginx/sites-available/reattend /etc/nginx/sites-enabled/reattend
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx

# ─── 13. SSL ──────────────────────────────────────────────────
log "Requesting LetsEncrypt certificates"
certbot --nginx -d "${DOMAIN_APP}" -d "${DOMAIN_NANGO}" \
  --non-interactive --agree-tos -m "$LETSENCRYPT_EMAIL" --redirect || \
  echo "  ⚠ certbot failed — check DNS propagation (dig +short ${DOMAIN_APP})"

# ─── 14. Backups cron ─────────────────────────────────────────
log "Installing hourly SQLite backup cron"
cat >/etc/cron.hourly/reattend-backup <<EOF
#!/bin/bash
TS=\$(date +%Y%m%d-%H)
sqlite3 ${DATA_DIR}/reattend.db ".backup ${DATA_DIR}/backups/reattend-\${TS}.db" 2>/dev/null || true
find ${DATA_DIR}/backups -type f -mtime +7 -delete 2>/dev/null || true
EOF
chmod +x /etc/cron.hourly/reattend-backup

# ─── Done ─────────────────────────────────────────────────────
cat <<EOF

────────────────────────────────────────────────────────────────
  Reattend Enterprise is up at:
    App:   https://${DOMAIN_APP}
    Nango: https://${DOMAIN_NANGO}

  Next steps (do these, in order):

  1. Verify the app loads:
       curl -I https://${DOMAIN_APP}

  2. Visit https://${DOMAIN_NANGO} in a browser, sign up for the
     Nango dashboard, and copy the Secret Key.

  3. On this droplet, edit ${ENV_FILE} and fill in:
       NANGO_SECRET_KEY=<the key you just copied>
       NANGO_WEBHOOK_SECRET=$(openssl rand -hex 16)
     Then restart:  systemctl restart reattend

  4. In Nango dashboard, set the webhook URL to:
       https://${DOMAIN_APP}/api/nango/webhook
     with the same NANGO_WEBHOOK_SECRET.

  5. Seed the demo org (one-time, optional):
       sudo -u ${APP_USER} bash -c "cd ${APP_DIR} && npm run seed:demo -- your@email.com"

  Logs:
    App:   journalctl -u reattend -f
    Nango: cd ${APP_DIR} && docker compose -f docker-compose.nango.yml logs -f

────────────────────────────────────────────────────────────────
EOF
